package com.aichat.workbench.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val WorkbenchLightColorScheme = lightColorScheme(
    primary = WorkbenchBrandColors.Emerald700,
    onPrimary = Color.White,
    primaryContainer = WorkbenchBrandColors.Mint50,
    onPrimaryContainer = Color(0xFF002114),
    secondary = Color(0xFF4A5568),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFEDF2F7),
    onSecondaryContainer = Color(0xFF1A202C),
    tertiary = WorkbenchBrandColors.Teal600,
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFCCFBF1),
    onTertiaryContainer = Color(0xFF042F2E),
    background = Color(0xFFF8FAFB),
    onBackground = WorkbenchBrandColors.Ink900,
    surface = Color.White,
    onSurface = WorkbenchBrandColors.Ink900,
    surfaceVariant = Color(0xFFF1F5F9),
    onSurfaceVariant = WorkbenchBrandColors.Slate500,
    surfaceContainer = Color(0xFFF1F5F9),
    surfaceContainerLow = Color(0xFFF8FAFB),
    surfaceContainerHigh = Color(0xFFE2E8F0),
    outline = Color(0xFFCBD5E1),
    outlineVariant = Color(0xFFE2E8F0),
    error = WorkbenchBrandColors.Red600,
    errorContainer = Color(0xFFFEF2F2),
    onError = Color.White,
    onErrorContainer = Color(0xFF991B1B),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    inversePrimary = Color(0xFF6EE7B7),
    surfaceTint = WorkbenchBrandColors.Emerald700,
)

internal val WorkbenchDarkColorScheme = darkColorScheme(
    primary = WorkbenchBrandColors.Emerald400,
    onPrimary = Color(0xFF003921),
    primaryContainer = WorkbenchBrandColors.Mint950,
    onPrimaryContainer = Color(0xFF6EE7B7),
    secondary = Color(0xFF94A3B8),
    onSecondary = Color(0xFF1E293B),
    secondaryContainer = Color(0xFF334155),
    onSecondaryContainer = Color(0xFFE2E8F0),
    tertiary = Color(0xFF2DD4BF),
    onTertiary = Color(0xFF042F2E),
    tertiaryContainer = Color(0xFF134E4A),
    onTertiaryContainer = Color(0xFFCCFBF1),
    background = Color(0xFF09090B),
    onBackground = Color(0xFFF1F5F9),
    surface = Color(0xFF0F0F11),
    onSurface = Color(0xFFF1F5F9),
    surfaceVariant = Color(0xFF1C1C1F),
    onSurfaceVariant = Color(0xFF94A3B8),
    surfaceContainer = Color(0xFF131316),
    surfaceContainerLow = Color(0xFF0F0F11),
    surfaceContainerHigh = Color(0xFF1C1C1F),
    outline = Color(0xFF3F3F46),
    outlineVariant = Color(0xFF27272A),
    error = WorkbenchBrandColors.Red400,
    errorContainer = Color(0xFF450A0A),
    onError = Color(0xFF2D0606),
    onErrorContainer = Color(0xFFFFD4D0),
    inverseSurface = Color(0xFFF1F5F9),
    inverseOnSurface = Color(0xFF1F2937),
    inversePrimary = WorkbenchBrandColors.Emerald700,
    surfaceTint = WorkbenchBrandColors.Emerald400,
)
